plugins {
    id 'com.android.application'
}

android {
    namespace 'com.dot3d.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.dot3d.app"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            // default debug config
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}